index:
  path: /
  controller: App\Controller\FacebookController::index
  methods: GET

app_facebookAdsManager_getAccInfo:
  path: /api/facebook/ads/manager
  controller: App\Controller\FacebookAdsManagerController::getAccInfo
  methods: GET