index:
  path: /
  controller: App\Controller\FacebookController::index
  methods: GET

app_facebookAdsManager_getAccInfo:
  path: /api/facebook/ads/manager/{action}
  controller: App\Controller\FacebookAdsManagerController::index
  methods: GET|POST